
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BACKWARD COLOR COLOR_BLUE COLOR_GREEN COLOR_RED FORWARD LEFT_PAREN LOOP NUMBER PEN RIGHT_PAREN ROTATE\n    expr : loop\n         | frcp\n               \n    loop : LOOP NUMBER LEFT_PAREN  expr RIGHT_PAREN expr\n    \n    frcp : forward expr\n         | backward expr\n         | rotate expr\n         | colorexp expr\n         | pen expr\n         | empty \n    \n    rotate :  ROTATE NUMBER\n\n    \n    backward : BACKWARD NUMBER\n\n    \n    forward :  FORWARD NUMBER\n\n    \n    pen : PEN NUMBER \n\n    \n    colorexp : COLOR COLOR_RED\n          | COLOR COLOR_BLUE\n          | COLOR COLOR_GREEN\n    \n    empty : \n\n    '
    
_lr_action_items = {'LOOP':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[4,4,4,4,4,4,-12,-11,-10,-14,-15,-16,-13,4,4,]),'FORWARD':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[11,11,11,11,11,11,-12,-11,-10,-14,-15,-16,-13,11,11,]),'BACKWARD':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[12,12,12,12,12,12,-12,-11,-10,-14,-15,-16,-13,12,12,]),'ROTATE':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[13,13,13,13,13,13,-12,-11,-10,-14,-15,-16,-13,13,13,]),'COLOR':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[14,14,14,14,14,14,-12,-11,-10,-14,-15,-16,-13,14,14,]),'PEN':([0,5,6,7,8,9,22,23,24,25,26,27,28,29,31,],[15,15,15,15,15,15,-12,-11,-10,-14,-15,-16,-13,15,15,]),'$end':([0,1,2,3,5,6,7,8,9,10,17,18,19,20,21,22,23,24,25,26,27,28,31,32,],[-17,0,-1,-2,-17,-17,-17,-17,-17,-9,-4,-5,-6,-7,-8,-12,-11,-10,-14,-15,-16,-13,-17,-3,]),'RIGHT_PAREN':([2,3,5,6,7,8,9,10,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,],[-1,-2,-17,-17,-17,-17,-17,-9,-4,-5,-6,-7,-8,-12,-11,-10,-14,-15,-16,-13,-17,31,-17,-3,]),'NUMBER':([4,11,12,13,15,],[16,22,23,24,28,]),'COLOR_RED':([14,],[25,]),'COLOR_BLUE':([14,],[26,]),'COLOR_GREEN':([14,],[27,]),'LEFT_PAREN':([16,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,5,6,7,8,9,29,31,],[1,17,18,19,20,21,30,32,]),'loop':([0,5,6,7,8,9,29,31,],[2,2,2,2,2,2,2,2,]),'frcp':([0,5,6,7,8,9,29,31,],[3,3,3,3,3,3,3,3,]),'forward':([0,5,6,7,8,9,29,31,],[5,5,5,5,5,5,5,5,]),'backward':([0,5,6,7,8,9,29,31,],[6,6,6,6,6,6,6,6,]),'rotate':([0,5,6,7,8,9,29,31,],[7,7,7,7,7,7,7,7,]),'colorexp':([0,5,6,7,8,9,29,31,],[8,8,8,8,8,8,8,8,]),'pen':([0,5,6,7,8,9,29,31,],[9,9,9,9,9,9,9,9,]),'empty':([0,5,6,7,8,9,29,31,],[10,10,10,10,10,10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> loop','expr',1,'p_expr','gui.py',74),
  ('expr -> frcp','expr',1,'p_expr','gui.py',75),
  ('loop -> LOOP NUMBER LEFT_PAREN expr RIGHT_PAREN expr','loop',6,'p_loop','gui.py',93),
  ('frcp -> forward expr','frcp',2,'p_frcp','gui.py',115),
  ('frcp -> backward expr','frcp',2,'p_frcp','gui.py',116),
  ('frcp -> rotate expr','frcp',2,'p_frcp','gui.py',117),
  ('frcp -> colorexp expr','frcp',2,'p_frcp','gui.py',118),
  ('frcp -> pen expr','frcp',2,'p_frcp','gui.py',119),
  ('frcp -> empty','frcp',1,'p_frcp','gui.py',120),
  ('rotate -> ROTATE NUMBER','rotate',2,'p_rotate','gui.py',132),
  ('backward -> BACKWARD NUMBER','backward',2,'p_backward','gui.py',140),
  ('forward -> FORWARD NUMBER','forward',2,'p_forward','gui.py',147),
  ('pen -> PEN NUMBER','pen',2,'p_pen','gui.py',156),
  ('colorexp -> COLOR COLOR_RED','colorexp',2,'p_color','gui.py',166),
  ('colorexp -> COLOR COLOR_BLUE','colorexp',2,'p_color','gui.py',167),
  ('colorexp -> COLOR COLOR_GREEN','colorexp',2,'p_color','gui.py',168),
  ('empty -> <empty>','empty',0,'p_empty','gui.py',176),
]
